<?php
$this->mainMenu()->setActiveItemId('imagesbeheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Images' => $this->url('beheer/images'),
]);
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">IMAGES BEHEER</h1>
</hgroup>
<!-- Breadcrumbs -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<p class="col-lg-12 col-md-12 col-sm-12">
    <span class="btn btn-default checkImages">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Check images
    </span>
</p>
<!-- Main Content -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <table class="table table-condensed table-bordered table-hover">
        <tr>
            <th class="text-center"><input type="checkbox" value="1" name="checkAll" /></th>
            <th>URL</th>
            <th>In database</th>
        </tr>
        <?php foreach ($images AS $index => $image) { ?>
        <tr id="img<?php echo $index; ?>">
            <td class="text-center"><input type="checkbox" value="<?php echo $index; ?>|<?php echo $image['url']; ?>" name="url"  /></td>
            <td>
                <?php echo $image['url']; ?>
            </td>
            <td class="result"></td>
        </tr>
        <?php } ?>
    </table>
</div>