<!-- Edit afbeelding -->
<div class="modal fade" id="editImage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Edit afbeelding</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <input type="hidden" name="imageId" value="" />
                    <div class="form-group row">
                        <label class="col-sm-4 col-md-4 col-lg-4 control-label" for="nameImage">Afbeelding naam</label>
                        <div class="col-sm-8 col-md-8 col-lg-8">
                            <input name="editNameImage" class="form-control" placeholder="Afbeelding naam" type="text" value="">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-md-4 col-lg-4 control-label" for="nameImage">Alt</label>
                        <div class="col-sm-8 col-md-8 col-lg-8">
                            <input name="editAlt" class="form-control" placeholder="Alt" type="text" value="">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-md-4 col-lg-4 control-label" for="nameImage">Omschrijving</label>
                        <div class="col-sm-8 col-md-8 col-lg-8">
                            <input name="editDdescriptionImage" class="form-control" placeholder="Omschrijving" type="text" value="">
                        </div>
                    </div>
                </form>
                <div class="modal-footer">
                    <button id="saveImageDetails" type="button" class="btn btn-default">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>