<?php
if ($pagination['totalPages'] > 1) { ?>
    <div class="row">
        <div class="col">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <!-- Previous page link -->
                    <?php if ($pagination['previousPage'] > 0) { ?>
                        <li class="page-item">
                            <a class="page-link" href="<?= $this->url($route['route'], ['action' => $route['action']], ['query' => ['page' => 1]]);?>" aria-label="Previous">
                                <i class="fas fa-fast-backward fa-xs"></i>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href=" <?= $this->url($route['route'], ['action' => $route['action']], ['query' => ['page' => $pagination['previousPage']]]);?>" aria-label="Previous">
                                <i class="fas fa-backward fa-xs"></i>
                            </a>
                        </li>
                        <?php if ($pagination['currentPage'] >= $pagination['pageRange']) { ?>
                            <li class="page-item">
                                <a class="page-link" href="<?= $this->url($route['route'], ['action' => $route['action']], ['query' => ['page' => 1,]]); ?>">1</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#"><i class="fas fa-ellipsis-h fa-xs"></i></a>
                            </li>
                        <?php } ?>
                    <?php } ?>
                    <!-- Numbered page links -->
                    <?php foreach ($pagination['pages'] AS $index => $page) { ?>
                        <?php if ($index >= $pagination['pageRangeStart'] && $index <= $pagination['pageRangeEnd']) { ?>
                            <li <?php echo ($page == $pagination['currentPage'] ? 'class="page-item active"' : 'class="page-item"') ?>>

                                <?php if ($page == $pagination['currentPage']) { ?>
                                    <span class="page-link"><?php echo $page; ?></span>
                                <?php } else { ?>
                                    <a class="page-link" href="<?= $this->url($route['route'], ['action' => $route['action']], ['query' => ['page' => $page]]); ?>"><?php echo $page; ?></a>
                                <?php } ?>
                            </li>
                        <?php } ?>
                    <?php } ?>

                    <!-- Next page link -->
                    <?php if ($pagination['currentPage'] <= $pagination['endRange']) { ?>
                        <li class="page-item">
                            <span class="page-link"><i class="fas fa-ellipsis-h fa-xs"></i></span>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="<?= $this->url($route['route'], ['page' => $pagination['totalPages'], 'action' => $route['action']], ['query' => ['page' => $pagination['totalPages']]]); ?>"><?php echo $pagination['totalPages']; ?></a>
                        </li>
                    <?php } ?>
                    <?php if ($pagination['nextPage'] <= $pagination['totalPages']) { ?>
                        <li class="page-item">
                            <a class="page-link" href="<?= $this->url($route['route'], ['page' => $pagination['nextPage'], 'action' => $route['action']], ['query' => ['page' => $pagination['nextPage']]]); ?>" aria-label="Next">
                                <i class="fas fa-forward fa-xs"></i>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="<?= $this->url($route['route'], ['page' => $pagination['totalPages'], 'action' => $route['action']], ['query' => ['page' => $pagination['totalPages']]]); ?>" aria-label="Previous">
                                <i class="fas fa-fast-forward fa-xs"></i>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            </nav>
        </div>
    </div>
<?php } ?>

