<?php
if ($paginationSettings['totalPages'] > 1) { ?>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link bg-dark text-white" href="<?= $this->url($route['route'], ['action' => $route['action']], ['query'=>['page'=>$paginationSettings['previousPage']]]); ?>" aria-label="Previous">
                    <i class="fas fa-angle-double-left"></i>
                </a>
            </li>

            <?php
            for ($page = 1; $page <= $paginationSettings['totalPages']; $page++) { ?>

                <li class="page-item bg-dark">
                    <a class="page-link bg-dark text-white" href="<?= $this->url($route['route'], ['action' => $route['action']], ['query'=>['page'=>$page]]); ?>"><?= $this->escapeHtml($page); ?></a>
                </li>

                <?php
            }
            ?>

            <li class="page-item">
                <a class="page-link bg-dark text-white" href="<?= $this->url($route['route'], ['action' => $route['action']], ['query'=>['page'=>$paginationSettings['nextPage']]]); ?>" aria-label="Previous">
                    <i class="fas fa-angle-double-right"></i>
                </a>
            </li>

        </ul>
    </nav>
    <?php
}
?>
