<!-- Modal PRogress bar images -->
<div class="modal fade" id="progressBarModal" tabindex="-1" aria-labelledby="progressBarModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-primary" id="progressBarModalLabel">Progress</h1>
      </div>
      <div class="modal-body">
          <div id="progressBar" class="progress" role="progressbar" aria-label="Basic example" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
              <div class="progress-bar bg-success" ></div>
          </div>
          <h4 class="mt-4 text-primary">Ontbrekende bestand(en)</h4>
          <div id="imageResults" class="container-fluid mt-3">

          </div>

      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
