<!-- Image upload -->
<?php
$fieldset = $form->get('upload-image');
$image = $fieldset->get('image');
?>
<hr/>
<h2>Afbeelding toevoegen</h2>
<div class="form-group row mt-3 mb-3">
    <?= $this->formLabel($image) ?>
    <div class="col-sm-6 col-md-6 col-lg-6">
            <label class="sr-only" for="inlineFormInputGroup">Username</label>
            <div class="input-group mb-2">
                <div class="input-group-prepend input-group-addon">
                    <label class="input-group-text  btn btn-primary btn-file">
                        Browse&hellip; <?= $this->formElement($image) ?>
                    </label>
                </div>
                <input type="text" class="form-control" name="fileUploadFileName" readonly>
            </div>
    </div>
</div>
<?php
$nameImage = $fieldset->get('nameImage');
?>
<div class="form-group row">
    <?= $this->formLabel($nameImage) ?>
    <div class="col-sm-6 col-md-6 col-lg-6">
        <?= $this->formElement($nameImage) ?>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6">

    </div>
</div>
<?php
$alt = $fieldset->get('alt');
?>
<div class="form-group row">
    <?= $this->formLabel($alt) ?>
    <div class="col-sm-6 col-md-6 col-lg-6">
        <?= $this->formElement($alt) ?>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6">

    </div>
</div>
<?php
$descriptionImage = $fieldset->get('descriptionImage');
?>
<div class="form-group row">
    <?= $this->formLabel($descriptionImage) ?>
    <div class="col-sm-6 col-md-6 col-lg-6">
        <?= $this->formElement($descriptionImage) ?>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6">
    </div>
</div>
<hr/>