<!-- Image upload -->
<hr/>
<h2>Afbeelden toevoegen</h2>
<div class="form-group">
    <?php echo $this->formLabel($formImage->get('image')); ?>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <div class="has-feedback">
            <div class="input-group">
                <label class="input-group-addon btn btn-file">
                    Browse&hellip; <input type="file" name="image" style="display: none;" multiple>
                </label>
                <input type="text" class="form-control" name="blogImageFileName" readonly>
            </div>
        </div>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php echo (count($formImage->getMessages('image')) > 0 ? $formImage->getMessages('image')['isEmpty'] : '&nbsp;' ) ?>
    </div>
</div>
<div class="form-group">
    <?php echo $this->formLabel($formImage->get('nameImage')); ?>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php echo $this->formText($formImage->get('nameImage')); ?>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php echo (count($formImage->getMessages('nameImage')) > 0 ? $formImage->getMessages('nameImage')['isEmpty'] : '&nbsp;' ) ?>
    </div>
</div>
<div class="form-group">
    <?php echo $this->formLabel($formImage->get('alt')); ?>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php echo $this->formText($formImage->get('alt')); ?>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php echo (count($formImage->getMessages('alt')) > 0 ? $formImage->getMessages('alt')['isEmpty'] : '&nbsp;' ) ?>
    </div>
</div>
<div class="form-group">
    <?php echo $this->formLabel($formImage->get('descriptionImage')); ?>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php echo $this->formText($formImage->get('descriptionImage')); ?>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php echo (count($formImage->getMessages('descriptionImage')) > 0 ? $formImage->getMessages('descriptionImage')['isEmpty'] : '&nbsp;' ) ?>
    </div>
</div>
<hr/>